name: CI workflow

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install front
        run: 
          npm install
      - name: Build
        run: 
          npm run tsc-check
      - name: Tests front
        run: 
          npm test
